name: noonpool_web
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  async: ^2.11.0
  auto_route: ^5.0.4
  base32: ^2.1.3
  cached_network_image: ^3.2.3
  clipboard: ^0.1.3
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.3.8
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  get: ^4.6.5
  http: ^1.1.0
  intl: ^0.18.1
  localization: ^2.1.0
  lottie: ^2.6.0
  otp: ^3.1.4
  pinput: ^3.0.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.12

dev_dependencies:
  auto_route_generator: ^5.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/mini_logo.png" 
  web:
    generate: true
    image_path: "assets/images/mini_logo.png"
    background_color: "#FFFFFF00"
    theme_color: "#3F2D14"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/onboarding/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500


